# Dependabot configuration for automated dependency updates
# This helps maintain security by keeping dependencies up to date

version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"

  # Enable version updates for Python pip dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      include: "scope"
    # Ignore major version updates for stability
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Monitor pixi.toml for conda/pip dependencies
  - package-ecosystem: "pip"
    directory: "/analytics_framework"
    schedule:
      interval: "weekly"
      day: "wednesday"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"