# This environment.yml file would create an environment called journey
# The newly created environment would be installed inside the ~/miniconda3/envs/ directory, unless we specified a different path using --prefix

name: journey
channels:
  - conda-forge
dependencies:
  - python=3.10
  - intake=0.6.5
  - Werkzeug=2.2.2
  - pre-commit
  - matplotlib
  - numpy
  - pandas
  - pip
  - pytest
  - requests
  - seaborn
  - scipy
  - scikit-learn
  - statsmodels
  - urllib3
  - hvplot
  - dagster=0.15.3
  - dagit=0.15.3
  - panel
  - holoviews
  - scikit-learn
  - aiohttp
  - python-fasthtml
  - pip:
    - mitoinstaller
    - quarto
    - openai
    - azure-ai-inference
