# This environment.yml file would create an environment called journey
# The newly created environment would be installed inside the ~/miniconda3/envs/ directory, unless we specified a different path using --prefix

name: journey
channels:
  - conda-forge
dependencies:
  - python=3.8
  - intake
  - pre-commit
  - matplotlib
  - numpy
  - pandas
  - pip
  - pytest
  - requests
  - seaborn
  - scipy
  - scikit-learn
  - statsmodels
  - urllib3
  - hvplot
  - pip:
      dagster
