[project]
authors = ["sayantikabanik <sayantikabanik122@gmail.com>"]
channels = ["conda-forge"]
description = "Your Open-Source Data management framework"
name = "journey"
platforms = ["linux-64", "osx-64", "win-64", "osx-arm64"]
version = "0.1.0"

[dependencies]
python = "3.10.*"
intake = "0.6.5.*"
werkzeug = "2.2.2.*"
pre-commit = "*"
matplotlib = "*"
numpy = "*"
pandas = "*"
pip = "*"
pytest = "*"
requests = "*"
seaborn = "*"
scipy = "*"
scikit-learn = "*"
statsmodels = "*"
urllib3 = "*"
hvplot = "*"
dagster = "1.8.13.*"
dagit = "1.8.13.*"
holoviews = "*"
aiohttp = "*"
python-fasthtml = "*"
alembic = ">=1.13.3,<2"

[pypi-dependencies]
mitoinstaller = "*"
panel = "*"
watchfiles = "*"
quarto = "*"
openai = "*"
azure-ai-inference = "*"

[tasks]
GIT_TOKEN_CHECK = "os.getenv(GITHUB_TOKEN)"
DJ_package = "pip install --editable . --use-pep517"
DJ_pre_commit = "pre-commit install"
DJ_dagster = { cmd = "dagit -f process.py", depends-on = "DJ_package", cwd = "analytics_framework/pipeline" }
DJ_panel_app = { cmd = "python stock_price_twilio_app.py", depends-on = "DJ_package", cwd = "analytics_framework/dashboard" }
DJ_flask_app = { cmd = "python app.py", depends-on = "DJ_package", cwd = "analytics_framework/intake/web_ui_flask" }
DJ_fasthtml_app = { cmd = "python app.py", depends-on = "DJ_package", cwd = "analytics_framework/intake/web_ui_fasthtml" }
DJ_mito_app = { cmd = "jupyter notebook mito_exp.ipynb", depends-on = "DJ_package", cwd = "usage_guide"}
DJ_llm_analysis = {cmd = "python analyse_my_data__gpt_4o_mini.py", cwd= "analytics_framework/ai_modeling"}
