[project]
authors = ["sayantikabanik <sayantikabanik122@gmail.com>"]
channels = ["conda-forge"]
description = "Your Open-Source Data management framework"
name = "journey"
platforms = ["linux-64", "osx-64", "win-64", "osx-arm64"]
version = "0.1.0"

[dependencies]
python = "3.10.*"
intake = "0.6.5.*"
werkzeug = "2.2.2.*"
pre-commit = "*"
matplotlib = "*"
numpy = "*"
pandas = "*"
pip = "*"
pytest = "*"
requests = "*"
seaborn = "*"
scipy = "*"
scikit-learn = "*"
statsmodels = "*"
urllib3 = "*"
hvplot = "*"
dagster = "1.8.13.*"
dagit = "1.8.13.*"
holoviews = "*"
aiohttp = "*"
python-fasthtml = "*"
alembic = ">=1.13.3,<2"
datasets = ">=3.2.0,<4"
langchain-community = ">=0.3.14,<0.4"
langchain-anthropic = ">=0.3.1,<0.4"
langgraph = ">=0.2.60,<0.3"
pillow = ">=11.1.0,<12"
transformers = ">=4.47.1,<5"
langchain-openai = ">=0.3.3,<0.4"
rich-click = ">=1.8.6,<2"
tomlkit = ">=0.13.2,<0.14"

[pypi-dependencies]
mitoinstaller = "*"
panel = "*"
watchfiles = "*"
quarto = "*"
openai = "*"
azure-ai-inference = "*"
mistralai = "*"
langchain-deepseek = "*"

[tasks]
# operations_DJ
GIT_TOKEN_CHECK = { cmd = "os.getenv(GITHUB_TOKEN)" }
DJ_package = { cmd = "pip install --editable . --use-pep517" }
DJ_pre_commit = { cmd = "pre-commit install" }
# applications
DJ_dagster = { cmd = "dagit -f process.py", depends-on = "DJ_package", cwd = "analytics_framework/pipeline" }
DJ_panel_app = { cmd = "python stock_price_twilio_app.py", depends-on = "DJ_package", cwd = "analytics_framework/dashboard" }
DJ_flask_app = { cmd = "python app.py", depends-on = "DJ_package", cwd = "analytics_framework/intake/web_ui_flask" }
DJ_fasthtml_app = { cmd = "python app.py", depends-on = "DJ_package", cwd = "analytics_framework/intake/web_ui_fasthtml" }
DJ_mito_app = { cmd = "jupyter notebook mito_exp.ipynb", depends-on = "DJ_package", cwd = "usage_guide"}
# llm
DJ_llm_analysis_gpt_4o = {cmd = "python analyse_my_data__gpt_4o_mini.py", cwd = "analytics_framework/ai_modeling"}
DJ_advance_llm_analysis = {cmd = "pythonadvance_analysis_coral_bleeching__meta_Llama_3.py", cwd = "analytics_framework/ai_modeling"}
DJ_hello_world_langchain = {cmd = "python hello_world_lc.py", cwd = "analytics_framework/langchain"}
DJ_spanish_eng_translation = { cmd = "python demo_spanish_translation__deepseek_r1.py", cwd = "analytics_framework/ai_modeling"}
# miscellaneous
DJ_sync_dataset_trees = {cmd = "curl -v -o trees.csv 'https://people.sc.fsu.edu/~jburkardt/data/csv/trees.csv'", outputs = ["trees.csv"], cwd = "analytics_framework/intake/data"}
