# Moving from conda to pixi way of env management
# Read more: https://pixi.sh/dev/basic_usage/

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Env_check:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up env with pixi goodness
        uses: prefix-dev/setup-pixi@v0.8.0
        with:
          pixi-version: v0.34.0
          cache: true
      - run: pixi run DJ_package
      - run: pixi run DJ_pre_commit
