# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Env_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up env with pixi goodness
        uses: prefix-dev/setup-pixi@v0.8.0
        with:
          pixi-version: v0.34.0
          cache: false
          frozen: true
          activate-environment: true

#        uses: conda-incubator/setup-miniconda@master
#        with:
#          miniforge-variant: Miniforge3
#          miniforge-version: latest
#          activate-environment: journey
#          environment-file: environment.yml
#          python-version: ${{ matrix.python-version }}
#          auto-activate-base: false
#          channels: conda-forge
#          channel-priority: strict
#
#      - name: Install package
#        run: |
#          pip install -e .
##       - name: Test with pytest
##         run: |
##           pytest tests/package.py
#      - name: Conda info
#        run: conda info
#      - name: Conda list
#        run: conda list
