name: Monitor GitHub API Rate Limit

permissions:
  contents: read

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch: # Allows manual trigger

jobs:
  check-rate-limit:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Monitor GitHub API Rate Limit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching rate limit information..."
          curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/rate_limit | jq '.'

      - name: Log rate limit to file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/rate_limit > rate_limit.json
          echo "Rate limit logged to rate_limit.json"

      - name: Upload rate limit log (optional)
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: rate-limit-log
          path: rate_limit.json
