name: Lint prose
on:
  pull_request:

# manually trigger based on requirement
  workflow_dispatch:

jobs:
  lint-prose:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Vale
      uses: errata-ai/vale-action@reviewdog
      with:
        files: all
#        vale_flags: --glob=!*/*-fr/*
        filter_mode: file
        reporter: github-pr-check
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
