name: Lint prose
permissions:
  contents: read
on:
  pull_request:

# manually trigger based on requirement
  workflow_dispatch:

jobs:
  lint-prose:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Vale
      uses: errata-ai/vale-action@0c6ce076b2df6985b17df8ad7b85b36f1f8d5bdc # reviewdog
      with:
        files: all
        vale_flags: --glob=!*/*-fr/*
        fail_on_error: false
        filter_mode: diff_context
        reporter: github-pr-check
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
