name: Generate SBOM

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install CycloneDX tool
        run: |
          pip install cyclonedx-bom

      - name: Freeze current environment to temporary requirements.txt
        run: |
          pip freeze > requirements.txt

      - name: Generate SBOM from environment
        run: |
          cyclonedx-py environment --PEP-639 --short-PURLs -o sbom_info.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-report
          path: sbom_info.json
